/* La Sacra Corona — bilingual content (ES primary, EN secondary) + shared data.
   Attached to window.LSC. Components read LSC.content[lang] and LSC.data. */
(function () {
  const data = {
    phone: "666 57 76 19",
    phoneHref: "+34666577619",
    whatsapp: "34666577619",
    instagram: "lasacracorona",
    email: "hola@lasacracorona.es",
    rating: "4,9",
    reviews: "786",
    years: "15+",
    studios: "2",

    // style filter keys reused across Estilos + Galería
    styleKeys: ["realismo", "blackgrey", "fineart", "tradicional", "piercing"],
    styleDuo: {
      realismo: "duo-1", blackgrey: "duo-5", fineart: "duo-3",
      tradicional: "duo-4", piercing: "duo-2",
    },

    artists: [
      { id: "art-mateo", name: "Mateo Ríos",     since: "2011", ig: "mateo.rios.ink" },
      { id: "art-lucia", name: "Lucía Serrano",   since: "2014", ig: "lucia.fineline" },
      { id: "art-dante", name: "Dante Vega",      since: "2009", ig: "dante.vega.trad" },
      { id: "art-olivia",name: "Olivia Marín",    since: "2016", ig: "olivia.piercing" },
    ],

    // gallery: slot id + style tag + aspect ratio (for masonry rhythm)
    gallery: [
      { id: "g01", style: "realismo",    ar: "3 / 4",  duo: "duo-1" },
      { id: "g02", style: "blackgrey",   ar: "1 / 1",  duo: "duo-5" },
      { id: "g03", style: "fineart",     ar: "3 / 5",  duo: "duo-3" },
      { id: "g04", style: "tradicional", ar: "4 / 3",  duo: "duo-4" },
      { id: "g05", style: "blackgrey",   ar: "3 / 4",  duo: "duo-5" },
      { id: "g06", style: "realismo",    ar: "1 / 1",  duo: "duo-1" },
      { id: "g07", style: "piercing",    ar: "4 / 5",  duo: "duo-2" },
      { id: "g08", style: "fineart",     ar: "4 / 3",  duo: "duo-3" },
      { id: "g09", style: "tradicional", ar: "3 / 4",  duo: "duo-blood" },
      { id: "g10", style: "realismo",    ar: "3 / 5",  duo: "duo-1" },
      { id: "g11", style: "blackgrey",   ar: "4 / 3",  duo: "duo-5" },
      { id: "g12", style: "piercing",    ar: "1 / 1",  duo: "duo-2" },
    ],
  };

  const es = {
    nav: { estilos: "Estilos", artistas: "Artistas", galeria: "Galería", visita: "Estudios", reserva: "Reserva tu cita", proceso: "Cómo funciona" },
    proceso: {
      eyebrow: "Cómo funciona",
      title: "El proceso",
      lede: "De la idea al tatuaje en cuatro pasos. Sin sorpresas, sin prisa.",
      cta: "Reserva tu cita",
      steps: [
        { n: "01", title: "Cuéntanos", desc: "Rellena el formulario con tu idea, zona del cuerpo y referencias. Cuanto más detalle, mejor presupuesto." },
        { n: "02", title: "Presupuesto", desc: "En menos de 24 h te respondemos con precio estimado y proponemos el artista más afín a tu proyecto." },
        { n: "03", title: "Cita", desc: "Reservamos fecha, haces el depósito y el artista prepara el diseño a medida. Sin depósito no hay cita." },
        { n: "04", title: "Tinta", desc: "Sesión, tinta y alta en nuestro protocolo de cuidados. Seguimiento incluido hasta la cicatrización completa." },
      ],
    },
    hero: {
      eyebrow: "Estudio de tatuaje & piercing · Sevilla",
      since: "Desde 2009",
      titleA: "Tu historia,",
      titleB: "grabada en piel",
      lede: "Realismo, black & grey, fine art y tradición. Quince años marcando Sevilla con tinta que dura toda la vida.",
      cta: "Reserva tu cita",
      cta2: "Ver galería",
      scroll: "Desliza",
    },
    trust: { rating: "Valoración Google", reviews: "Reseñas", years: "Años de oficio", studios: "Estudios en Sevilla" },
    estilos: {
      idx: "01",
      eyebrow: "Lo que tatuamos",
      title: "Estilos",
      lede: "Cada piel pide un lenguaje distinto. Estos son los nuestros.",
      items: {
        realismo:    { name: "Realismo",        desc: "Retrato y detalle fotográfico. Luz, sombra y textura que respiran." },
        blackgrey:   { name: "Black & Grey",    desc: "El alma del estudio. Gradientes profundos, contraste y silencio." },
        fineart:     { name: "Fine Art",        desc: "Línea fina y composición de autor. Tatuaje como obra, no como adorno." },
        tradicional: { name: "Tradicional",     desc: "Línea sólida y color que aguanta décadas. La escuela de siempre." },
        piercing:    { name: "Piercing de lujo",desc: "Joyería de titanio y oro, anatomía precisa, cicatrización cuidada." },
      },
    },
    artistas: {
      idx: "02",
      eyebrow: "Las manos",
      title: "Artistas",
      lede: "Cuatro especialistas, un mismo umbral de exigencia.",
      since: "En el estudio desde",
      bios: {
        "art-mateo":  { role: "Realismo · Retrato",        bio: "Especialista en retrato a gran escala. Trabaja por sesiones largas, una pieza cada vez." },
        "art-lucia":  { role: "Black & Grey · Fine line",  bio: "Línea fina, botánica y ornamento. Precisión quirúrgica con mano de dibujante." },
        "art-dante":  { role: "Tradicional · Lettering",   bio: "Fundador. Old school, lettering y banderas. La memoria viva del estudio." },
        "art-olivia": { role: "Piercing · Joyería",        bio: "Piercing anatómico y joyería de alta gama. Implant-grade, nada menos." },
      },
      cta: "Reservar con un artista",
    },
    galeria: {
      idx: "03",
      eyebrow: "El archivo",
      title: "Galería",
      lede: "Trabajo real, cicatrizado y en proceso. Filtra por estilo.",
      all: "Todo",
      empty: "Sin piezas en este estilo todavía.",
      view: "Ampliar",
    },
    testimonios: {
      idx: "04",
      eyebrow: "Lo que dicen",
      title: "Reseñas",
      lede: "Cinco estrellas, una y otra vez. Esto es lo que nos cuentan.",
      items: [
        { q: "Dante me hizo mi primer tatuaje grande y no podría estar más orgulloso. La atención al detalle es brutal, el ambiente del estudio te hace sentir en buenas manos desde el primer minuto.", author: "Alejandro M.", style: "Tradicional", year: "2024" },
        { q: "Lucía es una máquina. Mi tatuaje de fine line tardó cuatro horas y no se notó el tiempo. Resultado impecable, líneas perfectas y cicatrización sin ningún problema.", author: "Carmen V.", style: "Fine Art", year: "2024" },
        { q: "El piercing de Olivia fue la mejor decisión. Joyería de calidad, técnica impecable y un seguimiento de cuidados excelente. La corona en mi oreja es lo más bonito que llevo.", author: "Laura F.", style: "Piercing", year: "2023" },
        { q: "Mateo me hizo un retrato de mi abuela en el brazo. Cuando lo vi terminado lloré. El hiperrealismo que consigue es algo que no había visto en Sevilla.", author: "Pablo R.", style: "Realismo", year: "2024" },
      ],
      google: "Ver todas las reseñas",
    },
    reservas: {
      idx: "05",
      eyebrow: "Empieza aquí",
      title: "Reserva tu cita",
      lede: "Cuéntanos qué tienes en mente. Respondemos en menos de 24 horas con presupuesto y artista.",
      call: "O llámanos directamente",
      steps: ["Estilo", "Artista", "Fecha", "Tus datos"],
      stepLabel: "Paso",
      of: "de",
      q_style: "¿Qué estilo buscas?",
      q_artist: "¿Tienes preferencia de artista?",
      q_artist_any: "Sin preferencia — asignadme el mejor",
      q_date: "¿Cuándo te vendría bien?",
      q_size: "Tamaño aproximado",
      sizes: ["Pequeño (< 8 cm)", "Mediano (8–18 cm)", "Grande (> 18 cm)", "Aún no lo sé"],
      f_name: "Nombre completo",
      f_phone: "Teléfono",
      f_email: "Email",
      f_idea: "Describe tu idea",
      f_idea_ph: "Motivo, zona del cuerpo, referencias…",
      back: "Atrás",
      next: "Siguiente",
      submit: "Pide tu cita",
      sending: "Enviando…",
      done_title: "Solicitud recibida",
      done_body: "Gracias. Te escribimos en menos de 24 h para cerrar fecha y presupuesto.",
      done_cta: "Enviar otra",
      err_required: "Campo obligatorio",
      err_email: "Email no válido",
      err_phone: "Teléfono no válido",
      summary: "Tu solicitud",
    },
    loc: {
      idx: "06",
      eyebrow: "Dónde encontrarnos",
      title: "Estudios",
      lede: "Dos espacios en el corazón de Sevilla. Solo con cita previa.",
      directions: "Cómo llegar",
      hoursLabel: "Horario",
      studios: [
        { id: "feria",  name: "Estudio Feria",  addr: "C/ Feria 35", city: "41003 Sevilla", hours: "Mar–Sáb · 11:00–20:00", tag: "Sede principal" },
        { id: "regina", name: "Estudio Regina", addr: "C/ Regina 12", city: "41003 Sevilla", hours: "Mié–Sáb · 12:00–21:00", tag: "Piercing & fine line" },
      ],
    },
    footer: {
      tagline: "Tinta que dura toda la vida.",
      reserva: "Reserva tu cita",
      cols: { visit: "Visítanos", follow: "Síguenos", legal: "Legal" },
      hours: "Mar–Sáb · 11:00–20:00",
      legal: ["Aviso legal", "Privacidad", "Cookies", "Cuidados del tatuaje"],
      rights: "Todos los derechos reservados.",
      made: "Sevilla, España",
    },
    wa: { label: "WhatsApp", msg: "Hola, me gustaría reservar una cita en La Sacra Corona." },
    lang: { switch: "EN", current: "ES" },
  };

  const en = {
    nav: { estilos: "Styles", artistas: "Artists", galeria: "Gallery", visita: "Studios", reserva: "Book your session", proceso: "How it works" },
    proceso: {
      eyebrow: "How it works",
      title: "The process",
      lede: "From idea to tattoo in four steps. No surprises, no rush.",
      cta: "Book your session",
      steps: [
        { n: "01", title: "Tell us", desc: "Fill in the form with your idea, body placement and references. The more detail, the better the quote." },
        { n: "02", title: "Quote", desc: "Within 24 h we reply with an estimate and suggest the artist most suited to your project." },
        { n: "03", title: "Appointment", desc: "We book a date, you pay the deposit and the artist prepares a bespoke design. No deposit, no appointment." },
        { n: "04", title: "Ink", desc: "Session, ink and onboarding into our aftercare protocol. Follow-up included until complete healing." },
      ],
    },
    hero: {
      eyebrow: "Tattoo & piercing studio · Seville",
      since: "Since 2009",
      titleA: "Your story,",
      titleB: "etched in skin",
      lede: "Realism, black & grey, fine art and tradition. Fifteen years marking Seville with ink that lasts a lifetime.",
      cta: "Book your session",
      cta2: "See gallery",
      scroll: "Scroll",
    },
    trust: { rating: "Google rating", reviews: "Reviews", years: "Years of craft", studios: "Studios in Seville" },
    estilos: {
      idx: "01",
      eyebrow: "What we tattoo",
      title: "Styles",
      lede: "Every skin asks for a different language. These are ours.",
      items: {
        realismo:    { name: "Realism",       desc: "Portrait and photographic detail. Light, shadow and texture that breathe." },
        blackgrey:   { name: "Black & Grey",  desc: "The soul of the studio. Deep gradients, contrast and silence." },
        fineart:     { name: "Fine Art",      desc: "Fine line and authored composition. Tattoo as work, not ornament." },
        tradicional: { name: "Traditional",   desc: "Solid line and colour that holds for decades. The old school." },
        piercing:    { name: "Luxury piercing",desc:"Titanium and gold jewellery, precise anatomy, careful healing." },
      },
    },
    artistas: {
      idx: "02",
      eyebrow: "The hands",
      title: "Artists",
      lede: "Four specialists, one standard.",
      since: "At the studio since",
      bios: {
        "art-mateo":  { role: "Realism · Portrait",       bio: "Large-scale portrait specialist. Long sessions, one piece at a time." },
        "art-lucia":  { role: "Black & Grey · Fine line", bio: "Fine line, botanical and ornament. Surgical precision, a draughtsman's hand." },
        "art-dante":  { role: "Traditional · Lettering",  bio: "Founder. Old school, lettering and flags. The studio's living memory." },
        "art-olivia": { role: "Piercing · Jewellery",     bio: "Anatomical piercing and high-end jewellery. Implant-grade, nothing less." },
      },
      cta: "Book with an artist",
    },
    galeria: {
      idx: "03",
      eyebrow: "The archive",
      title: "Gallery",
      lede: "Real work, healed and in progress. Filter by style.",
      all: "All",
      empty: "No pieces in this style yet.",
      view: "Expand",
    },
    testimonios: {
      idx: "04",
      eyebrow: "What they say",
      title: "Reviews",
      lede: "Five stars, time and again. Here's what our clients tell us.",
      items: [
        { q: "Dante did my first large tattoo and I couldn't be prouder. The attention to detail is incredible, and the studio atmosphere makes you feel in good hands from minute one.", author: "Alejandro M.", style: "Traditional", year: "2024" },
        { q: "Lucía is a machine. My fine line piece took four hours and it didn't even feel that long. Impeccable result, perfect lines and a smooth heal.", author: "Carmen V.", style: "Fine Art", year: "2024" },
        { q: "Olivia's piercing was the best decision. Quality jewellery, impeccable technique, and great aftercare follow-up. The crown on my ear is the most beautiful thing I wear.", author: "Laura F.", style: "Piercing", year: "2023" },
        { q: "Mateo did a portrait of my grandmother on my arm. When I saw it finished I cried. The photorealism he achieves is something I hadn't seen in Seville.", author: "Pablo R.", style: "Realism", year: "2024" },
      ],
      google: "See all reviews",
    },
    reservas: {
      idx: "05",
      eyebrow: "Start here",
      title: "Book your session",
      lede: "Tell us what you have in mind. We reply within 24 hours with a quote and an artist.",
      call: "Or call us directly",
      steps: ["Style", "Artist", "Date", "Your details"],
      stepLabel: "Step",
      of: "of",
      q_style: "Which style are you after?",
      q_artist: "Any artist preference?",
      q_artist_any: "No preference — match me with the best",
      q_date: "When would suit you?",
      q_size: "Approximate size",
      sizes: ["Small (< 8 cm)", "Medium (8–18 cm)", "Large (> 18 cm)", "Not sure yet"],
      f_name: "Full name",
      f_phone: "Phone",
      f_email: "Email",
      f_idea: "Describe your idea",
      f_idea_ph: "Subject, body area, references…",
      back: "Back",
      next: "Next",
      submit: "Request appointment",
      sending: "Sending…",
      done_title: "Request received",
      done_body: "Thank you. We'll write within 24h to confirm a date and quote.",
      done_cta: "Send another",
      err_required: "Required field",
      err_email: "Invalid email",
      err_phone: "Invalid phone",
      summary: "Your request",
    },
    loc: {
      idx: "06",
      eyebrow: "Where to find us",
      title: "Studios",
      lede: "Two spaces in the heart of Seville. By appointment only.",
      directions: "Directions",
      hoursLabel: "Hours",
      studios: [
        { id: "feria",  name: "Feria Studio",  addr: "C/ Feria 35", city: "41003 Seville", hours: "Tue–Sat · 11:00–20:00", tag: "Main studio" },
        { id: "regina", name: "Regina Studio", addr: "C/ Regina 12", city: "41003 Seville", hours: "Wed–Sat · 12:00–21:00", tag: "Piercing & fine line" },
      ],
    },
    footer: {
      tagline: "Ink that lasts a lifetime.",
      reserva: "Book your session",
      cols: { visit: "Visit us", follow: "Follow", legal: "Legal" },
      hours: "Tue–Sat · 11:00–20:00",
      legal: ["Legal notice", "Privacy", "Cookies", "Tattoo aftercare"],
      rights: "All rights reserved.",
      made: "Seville, Spain",
    },
    wa: { label: "WhatsApp", msg: "Hi, I'd like to book a session at La Sacra Corona." },
    lang: { switch: "ES", current: "EN" },
  };

  window.LSC = { data, content: { es, en } };
})();
